version: '3.9'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE=web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE=worker
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/app
    restart: always
    depends_on:
      - redis

